baseURL = "https://oldvan.pages.dev/"
languageCode = "zh-cn"
title = "老梵"
theme = "PaperMod"
paginate = 8

[params]
  mainSections = ["posts"]
  disableSpecial1stPost = true
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.author]
    name = "老梵"

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
